# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    branches: [ master, fix_workflow ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10", 3.11, 3.12]

    steps:
    - uses: actions/checkout@v2
    - name: Set up conda / Python
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: test
        python-version: ${{ matrix.python-version }}
        auto-activate-base: false
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install -c conda-forge pymultinest
        pip install nestle
        conda install pip pytest
        pip install .[QUfitting,parallel] --upgrade
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        cd tests/
        pytest *.py
